import ClientAuthInitiator from "@/components/auth/ClientAuthInitiator";
import Header from "@/components/common/common-header/Header";
import { Icons } from "@/components/common/icons";
import RecoilProvider from "@/stores";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import dayjs from "dayjs";
import "dayjs/locale/en";
import relativeTime from "dayjs/plugin/relativeTime";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import Link from "next/link";
import "react-tooltip/dist/react-tooltip.css";
import { twMerge } from "tailwind-merge";
import "./globals.css";

dayjs.locale("en");
dayjs.extend(relativeTime);

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();

  const supabase = createServerComponentClient({ cookies: () => cookieStore });
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        {user ? (
          <>
            <ClientAuthInitiator user={user}>
              <Header />
              <RecoilProvider>{children}</RecoilProvider>
            </ClientAuthInitiator>
          </>
        ) : (
          <div className="h-screen">
            <div
              className={ twMerge("fixed w-full flex items-center justify-center p-5")}
            >
              <Link href="/" className="flex items-center">
                <Icons.logoMinhKim className={"w-52"} />
              </Link>
            </div>
            {children}
          </div>
        )}
      </body>
    </html>
  );
}
